export const LABELS = {
	COMMON: {
		PROCCESING: "Procesando...",
		FREE: "Gratis",
		IMPORTANT: "Importante",
		IMPORTANT_TEXT_01:
			"Los envíos se realizan los días lunes por Correo Argentino",
		IMPORTANT_TEXT_02: "Los pagos se realizan por Mercado Pago",
		BACK_HOME: "Volver al inicio",
		SEARCHING: "Buscando",
		HOME: "Inicio",
	},
	CATEGORY: {
		NOT_FOUND: "Categoría no encontrada",
	},
	PRODUCT: {
		SINGULAR: "Producto",
		PLURAL: "Productos",
		NEW: "Nuevo",
		SOLD_OUT: "Agotado",
		NOT_FOUND: "Producto no encontrado",
	},
	PURCHASES: {
		MY_PURCHASES: "Mis Compras",
	},
	CART: {
		MY_CART: "Mi Carrito",
		RETRY_MESSAGE: "Intenta nuevamente mas tarde o comunicate con nosotros a",
		PRICE: "Precio",
		FINISH_PURCHASE: "Finalizar Compra",
		MAKE_PURCHASE: "Realizar Compra",
		ADD_TO_CART: "Añadir al carrito",
		QUANTITY: "Cantidad",
		SUBTOTAL: "Subtotal",
		TOTAL: "Total",
		SHIPPINGCOST: "Costo de envio",
		DISCOUNT: "Descuento",
		DISCOUNT_COUPON: "Cupon de descuento",
		PURCHASE_SUMMARY: "Resumen de la compra",
		TOTAL_PRODUCTS: "Total Productos",
		TOTAL_TO_PAY: "Total a pagar",
		PRODUCT: "Producto",
		NO_PRODUCTS: "No hay productos en el carrito",
		END_PURCHASE: "Finalizar Compra",
		FAILED_PURCHASE: "Compra Fallida",
		FAILED_PURCHASE_TEXT: "No se ha podido procesar el pago",
		PURCHASE_DONE: "Compra Realizada",
		PURCHASE_DONE_TEXT: "Compra exitosa!",
		PURCHASE_DONE_SUBTEXT: "Nos pondremos en contacto a la brevedad",
	},
};
